# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  backup:
    env_file:
      - .env
    build:
      context: .
      args:
        ALPINE_VERSION: '3.16'
    environment:
      SCHEDULE: ${SCHEDULE} # optional
      BACKUP_KEEP_DAYS: ${BACKUP_KEEP_DAYS} # optional
      PASSPHRASE: ${PASSPHRASE} # optional
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./backup:/data

volumes:
  backup:
    driver: local
